#!/usr/bin/perl

use strict;
use warnings;

use File::Path;

# xml'и складываем в папку xml.

mkpath('xml');

my $N_LABELS = 7;

#######################################################################################################################

write_test("s3", 3, \&test_simple);
write_test("s1000", 1000, \&test_simple);
write_test("s5000", 5000, \&test_simple);
write_test("s10000", 10000, \&test_simple);
write_test("s25000", 25000, \&test_simple);

write_test("l3", 3, \&test_complex);
write_test("l1000", 1000, \&test_complex);
write_test("l5000", 5000, \&test_complex);
write_test("l10000", 10000, \&test_complex);
write_test("l25000", 25000, \&test_complex);

#######################################################################################################################

sub write_test {
    my ($prefix, $count, $content) = @_;

    my $xml = &$content($count);

    write_file("${prefix}.xml", $xml);
    write_file("${prefix}_.xml", mod_noindents($xml));

    my $xmlns = mod_ns($xml);
    write_file("${prefix}ns.xml", $xmlns);
    write_file("${prefix}ns_.xml", mod_noindents($xmlns));
}

sub write_file {
    my ($filename, $content) = @_;

    my $F;
    open($F, ">xml/$filename");
    print $F <<XML;
<?xml version="1.0" encoding="utf-8"?>

<test xmlns:ya="http://www.yandex.ru">
XML
    print $F $content;
    print $F <<XML;
</test>

XML
    close($F);
}

#######################################################################################################################

sub test_simple {
    my ($count) = @_;

    return items($count, \&item_simple);
}

sub test_complex {
    my ($count) = @_;

    return html() . labels() . items($count, \&item_complex);
}

#######################################################################################################################

sub items {
    my ($count, $item) = @_;

    my $r = <<XML;
    <items>
XML
    $r .= join('', map { &$item($_) } 1..$count);
    $r .= <<XML;
    </items>
XML
}

#######################################################################################################################

sub item_simple {
    my ($i) = @_;

    return <<XML;
        <item id="$i">
            <id>$i</id>
            <text>$i</text>
        </item>
XML

}

sub item_complex {
    my ($i) = @_;

    my $label_id = $i % $N_LABELS;

    return <<XML;
        <item id="$i">
            <id>$i</id>
            <text>text $i</text>
            <label id="$label_id"/>
            <subitem-1>
                <subitem-2>
                    <subitem-3>
                        <subitem-4>
                            <subitem-5>
                                <subitem-6>
                                    <subitem-7 id="$i">
                                        <id>$i</id>
                                        <text>subtext $i</text>
                                    </subitem-7>
                                </subitem-6>
                            </subitem-5>
                        </subitem-4>
                    </subitem-3>
                </subitem-2>
            </subitem-1>
        </item>
XML
}

#######################################################################################################################

sub mod_ns {
    my ($xml) = @_;

    if ($xml =~ m{<html>.*</html>}) {
        $xml =~ s{(.*)<html>}{ ns($1) . '<html>'; }egsm;
        $xml =~ s{</html>(.*?)<html>}{ '</html>' . ns($1) . '<html>'; }egsm;
        $xml =~ s{</html>(.*)}{ '</html>' . ns($1); }egsm;
    } else {
        $xml = ns($xml);
    }

    return $xml;
}

sub ns {
    my ($xml) = @_;

    $xml =~ s{<(\w+)}{<ya:$1}gsm;
    $xml =~ s{</(\w+)}{</ya:$1}gsm;

    return $xml;
}

sub mod_noindents {
    my ($xml) = @_;

    $xml =~ s{>\s+<}{><}gsm;
    $xml =~ s{(\?>)}{$1\n\n}sm;

    return $xml;
}

#######################################################################################################################

sub html {
    return <<HTML;
    <html>
        <div class="b-folders">
            <div class="b-folders__folder b-folders__folder_current b-folders__folder_unread">
                <i class="b-folders__folder__arrow"/>
                <a href="" class="b-folders__folder__link"><span class="b-folders__folder__text">Входящие</span></a>
                <span class="b-folders__folder__info"><span class="b-folders__counters"><a href="#" class="b-folders__folder__link">23</a> / 90</span></span>
            </div>
            <div class="b-folders__folder b-folders__folder_custom">
                <i class="b-folders__folder__arrow"/>
                <a href="" class="b-folders__folder__link"><span class="b-folders__folder__text">Без иконки</span></a>
                <span class="b-folders__folder__info"><span class="b-folders__counters">13</span></span>
            </div>
            <div class="b-folders__folder b-folders__folder_custom b-folders__folder_unread">
                <i class="b-folders__folder__arrow"/>
                <a href="" class="b-folders__folder__link"><span class="b-folders__folder__text">Переписка с Кауцким</span></a>
                <span class="b-folders__folder__info"><span class="b-folders__counters"><a href="#" class="b-folders__folder__link">228</a> / 123450</span></span>
            </div>
            <div class="b-folders__folder b-folders__folder_custom b-folders__folder_unread">
                <i class="b-folders__folder__arrow"/>
                <a href="" class="b-folders__folder__link"><img src="/blocks/b-folders/icon/_icon/b-folders__icon_odnoklassniki.gif" class="b-folders__icon" alt=""/><span class="b-folders__folder__text">Одноклассники</span></a>
                <span class="b-folders__folder__info"><span class="b-folders__counters"><a href="#" class="b-folders__folder__link">2</a> / 906</span></span>
            </div>
            <div class="b-folders__folder b-folders__folder_custom">
                <i class="b-folders__folder__arrow"/>
                <a href="" class="b-folders__folder__link"><img src="//favicon.yandex.net/favicon/blogs.mail.ru" class="b-folders__icon" alt=""/><span class="b-folders__folder__text">Внешняя иконка</span></a>
                <span class="b-folders__folder__info"><span class="b-folders__counters">13</span></span>
            </div>
            <div class="b-folders__folder">
                <i class="b-folders__folder__arrow"/>
                <a href="" class="b-folders__folder__link"><span class="b-folders__folder__text">Отправленные</span></a>
                <span class="b-folders__folder__info"><span class="b-folders__counters">60</span></span>
            </div>
            <div class="b-folders__folder">
                <i class="b-folders__folder__arrow"/>
                <a href="" class="b-folders__folder__link"><span class="b-folders__folder__text">Удалённые</span></a>
                <span class="b-folders__folder__info">
                    <a href="#"><img alt="[x]" title="Очистить" src="/blocks/b-folders/folder/b-folders__folder__clean.gif" class="b-folders__folder__clean"/></a>
                    <span class="b-folders__counters">2</span>
                </span>
            </div>
            <div class="b-folders__folder">
                <i class="b-folders__folder__arrow"/>
                <a href="" class="b-folders__folder__link"><span class="b-folders__folder__text">Спам</span></a>
                <span class="b-folders__folder__info">
                    <a href="#"><img alt="[x]" title="Очистить" src="/blocks/b-folders/folder/b-folders__folder__clean.gif" class="b-folders__folder__clean"/></a>
                    <span class="b-folders__counters">6</span>
                </span>
            </div>
            <div class="b-folders__folder">
                <i class="b-folders__folder__arrow"/>
                <a href="" class="b-folders__folder__link"><span class="b-folders__folder__text">Ну очень-очень длинное имя папки-шмапки</span></a>
                <span class="b-folders__folder__info">
                    <a href="#"><img alt="[x]" title="Очистить" src="/blocks/b-folders/folder/b-folders__folder__clean.gif" class="b-folders__folder__clean"/></a>
                    <span class="b-folders__counters">6</span>
                </span>
            </div>
            <div class="b-folders__folder">
                <i class="b-folders__folder__arrow"/>
                <a href="" class="b-folders__folder__link"><span class="b-folders__folder__text">Черновики</span></a>
                <span class="b-folders__folder__info"><span class="b-folders__counters">30</span></span>
            </div>
            <div class="b-folders__setup"><a href="/setup_folders/" class="b-folders__setup__link">настроить…</a></div>
        </div>
    </html>
HTML
}

#######################################################################################################################

sub labels {
    my $r = <<XML;
    <labels>
XML
    for (my $i = 1; $i <= $N_LABELS; $i++) {
        $r .= <<XML;
        <label id="$i">label $i</label>
XML
    }
    $r .= <<XML;
    </labels>
XML

    return $r;
}

#######################################################################################################################

